@extends('layouts.master')
@section('container')
@include('user.cabai.lahan360')
@include('user.cabai.detailtumbuhan')
@include('user.cabai.pertumbuhan')
@include('user.cabai.pemupukan')
@include('user.cabai.kesuburan')
@include('user.cabai.map')
@endsection
