@extends('layouts.master')
@section('container')
@include('user.nila.kolam360')
@include('user.nila.detailnila')
@include('user.nila.perkembangan')
@include('user.nila.pakan')
@include('user.nila.kolam')
@include('user.nila.map')
@endsection
