@extends('layouts.master')
@section('container')
@include('admin.kelolakomoditi.detailcabai.lahan360')
@include('admin.kelolakomoditi.detailcabai.detailtumbuhan')
@include('admin.kelolakomoditi.detailcabai.pertumbuhan')
@include('admin.kelolakomoditi.detailcabai.pemupukan')
@include('admin.kelolakomoditi.detailcabai.kesuburan')
@include('admin.kelolakomoditi.detailcabai.map')
@endsection
